// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_jpr_dashboard/test/features/member/data/repositories/member_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_jpr_dashboard/core/network/network_info.dart' as _i6;
import 'package:flutter_jpr_dashboard/feature/member/data/datasources/member_local_datasource.dart'
    as _i5;
import 'package:flutter_jpr_dashboard/feature/member/data/datasources/member_remote_datasource.dart'
    as _i3;
import 'package:flutter_jpr_dashboard/feature/member/data/models/member_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMemberModel_0 extends _i1.Fake implements _i2.MemberModel {}

/// A class which mocks [MemberRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRemoteDataSource extends _i1.Mock
    implements _i3.MemberRemoteDataSource {
  MockMemberRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MemberModel>> getMemberList() => (super.noSuchMethod(
          Invocation.method(#getMemberList, []),
          returnValue: Future<List<_i2.MemberModel>>.value(<_i2.MemberModel>[]))
      as _i4.Future<List<_i2.MemberModel>>);
  @override
  _i4.Future<_i2.MemberModel> getMember(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMember, [id]),
              returnValue: Future<_i2.MemberModel>.value(_FakeMemberModel_0()))
          as _i4.Future<_i2.MemberModel>);
  @override
  _i4.Future<_i2.MemberModel> createMember(_i2.MemberModel? memberModel) =>
      (super.noSuchMethod(Invocation.method(#createMember, [memberModel]),
              returnValue: Future<_i2.MemberModel>.value(_FakeMemberModel_0()))
          as _i4.Future<_i2.MemberModel>);
  @override
  _i4.Future<_i2.MemberModel> updateMember(int? id, _i2.MemberModel? member) =>
      (super.noSuchMethod(Invocation.method(#updateMember, [id, member]),
              returnValue: Future<_i2.MemberModel>.value(_FakeMemberModel_0()))
          as _i4.Future<_i2.MemberModel>);
  @override
  _i4.Future<bool> removeMember(int? id) =>
      (super.noSuchMethod(Invocation.method(#removeMember, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [MemberLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberLocalDataSource extends _i1.Mock
    implements _i5.MemberLocalDataSource {
  MockMemberLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MemberModel>> getLastMemberList() => (super.noSuchMethod(
          Invocation.method(#getLastMemberList, []),
          returnValue: Future<List<_i2.MemberModel>>.value(<_i2.MemberModel>[]))
      as _i4.Future<List<_i2.MemberModel>>);
  @override
  _i4.Future<void> cacheMemberList(List<_i2.MemberModel>? memberListToCache) =>
      (super.noSuchMethod(
          Invocation.method(#cacheMemberList, [memberListToCache]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
